AppBundle\Entity\Claim:
    type: entity
    table: claim
    uniqueConstraints:
        usercard_index:
            columns: [ decklist_id, client_id, name, rank ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        decklist:
            targetEntity: Decklist
            nullable: false
            inversedBy: claims
            joinColumn:
                name: decklist_id
                referencedColumnName: id
        client:
            targetEntity: Client
            nullable: true
            inversedBy: claims
            joinColumn:
                name: client_id
                referencedColumnName: id
        user:
            targetEntity: User
            nullable: true
            joinColumn:
                name: user_id
                referencedColumnName: id
    fields:
        name:
            type: string
            length: '255'
        url:
            type: string
            length: '255'
        rank:
            column: "`rank`"
            type: smallint
        participants:
            type: smallint
    lifecycleCallbacks: {  }
