AppBundle\Entity\MwlCard:
    type: entity
    table: mwl_card
    manyToOne:
        mwl:
            targetEntity: Mwl
            nullable: false
            joinColumn:
                name: mwl_id
                referencedColumnName: id
        card:
            targetEntity: Card
            nullable: false
            joinColumn:
                name: card_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        mwl_id:
            type: integer
        card_id:
            type: integer
        global_penalty:
            type: integer 
            nullable: true
        universal_faction_cost:
            type: integer 
            nullable: true
        is_restricted:
            type: boolean 
            nullable: true
        is_banned:
            type: boolean 
            nullable: true
    lifecycleCallbacks: {  }
